---
title: "Homework 1"
author: "Isabel Leiva"
date: "`r format(Sys.Date(), '%B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 1
    css: !expr here::here("./StylesTemplates/il_26.css")
---

```{r setup, include=F}
knitr::opts_chunk$set(fig.width=8, fig.height=5, fig.align = 'left', fig.path='Figs/', cache.path='Cache/', eval=T, echo=T, tidy=TRUE,  cache=F, message=F, warning=F, stringsAsFactors=F, yaml.eval.expr = TRUE)  

library(xfun)
pkg_attach("tidyverse", "here", "kableExtra", "RCurl", "psych", "knitr", "RColorBrewer", 'dplyr', install=T)

#prints output with these specifications
jamie.theme <- theme_bw() + theme(axis.line = element_line(colour = "black"), panel.grid.minor = element_blank(), panel.grid.major = element_blank(), panel.border = element_blank(), panel.background = element_blank(), legend.title= element_blank())  #custom theme ggplot2


print.me <- function(x, ...) {
if (nrow(x) > 200){
   len <- 200 
    } else {
       len <- (nrow(x))
}
   x[1:len,] %>%
   kbl(digits=2, align= 'l', booktabs=T) %>%
   kable_styling(fixed_thead = T) %>%
   kable_paper("striped", full_width = T, html_font = "Blippo", font_size = 12) %>%
   row_spec(0, color = "white", background = "#9DC2A1", font_size = 12, bold = TRUE) %>%
   #scroll_box(width = "700px", height = "500px") %>%
   asis_output()
}
registerS3method("knit_print", "data.frame", print.me)
#to_R <- read.csv(here("data", "MyRaw.txt")) ---- using 'here' to read in data
```

# Instructions
1) Produce a string "Mary Had A Little Lamb" in one block
2) Split the string into one word per row
3) Add a variable called Nletters that counts the letters in each word.

# Mary Sentence Printing
```{r}
rhyme <- c("Mary Had A Little Lamb") #creating a vector with this phrase called "rhyme"
rhyme #calling the rhyme vector to print
```
# Mary Sentence Split
```{r}
rhyme_df <- tibble(rhyme) #making the rhyme vector a dataframe (df)
rhyme_df <- rhyme_df %>% rename(Word = rhyme) #renaming the column to "word"
rhyme_words <- tibble(separate_longer_delim(rhyme_df,cols = Word, delim = " ")) #printing each word in rhyme individually
rhyme_words #calling the df to print
```
# Mary Character Count
```{r}
rhyme_words$Nletter <- apply(rhyme_words, 1, nchar) #applying the nchar counting function to each row and creating a new row the the results called Nletter
rhyme_words #calling the df to print
```




